import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from PIL import Image
import os

from utils.data_fetcher import DataFetcher
from utils.portfolio_analyzer import PortfolioAnalyzer
from utils.recommendation_engine import RecommendationEngine
from utils.advanced_metrics import AdvancedMetricsCalculator
from components.dashboard import Dashboard
from components.sector_analysis import SectorAnalysis
from components.stock_performance import StockPerformance
from components.benchmark_comparison import BenchmarkComparison
from components.recommendations import Recommendations
from components.customer_profile import CustomerProfile
from components.rebalancing import PortfolioRebalancing
from components.historical_performance import HistoricalPerformance
from components.advanced_metrics_tab import render_advanced_metrics_tab
from utils.pdf_generator import PDFReportGenerator
from components.homepage import (
    render_modern_homepage, render_upload_section, render_features_section,
    render_how_it_works_section, render_cta_section, render_csv_requirements,
    render_insights_section, render_footer, render_methodology_section, render_metrics_section
)

def init_database():
    if os.environ.get('DATABASE_URL'):
        try:
            from utils.database import Database
            db = Database()
            db.init_tables()
            db.seed_initial_data()
            return True
        except Exception as e:
            print(f"Database initialization failed: {e}")
    return False

def render_disclaimer_overlay(section_type):
    """Render disclaimer as an overlay on top of blurred content preview"""
    
    preview_text = "Investment Recommendations" if section_type == 'advice' else "Portfolio Rebalancing Suggestions"
    
    st.info(f"{preview_text} are available below. Please read and accept the disclaimer to view.")
    
    st.markdown("### Disclaimer – Investment Advice & Portfolio Rebalancing")
    
    with st.container(border=True):
        st.markdown("""
The investment advice, recommendations, and portfolio rebalancing suggestions displayed on thealphalens.com are algorithmic outputs generated by proprietary Growth and Value investing models. These models are based on widely accepted investment frameworks, including Value Investing principles popularised by Benjamin Graham and Warren Buffett and Growth Investing methodologies, using quantitative financial, price, and momentum data.

The recommendations are derived from a rule-based scoring system that evaluates stocks across multiple parameters such as valuation metrics, growth indicators, financial ratios, price performance, and market positioning. Final BUY, HOLD, or SELL signals are generated through a combined scoring logic that blends Value and Growth perspectives.

**These outputs are not the result of any individual analyst's, advisor's, or portfolio manager's judgment.**

---

**Important Clarifications:**

- This tool **does not provide personalised investment advice** and does not consider your individual financial situation, investment objectives, risk appetite, tax status, or liquidity needs.

- The advice and rebalancing suggestions are purely **model-driven, informational, and educational** in nature.

- **Past performance, model outputs, or scores do not guarantee future results.** Financial markets are inherently volatile and subject to economic, political, regulatory, and market risks.

---

**User Acknowledgement & Risk Acceptance:**

By accessing, viewing, or acting upon the Advice or Rebalance sections of the analysis, you expressly acknowledge and agree that:

1. You understand that all recommendations are **indicative, probabilistic, and based on historical and current data assumptions.**

2. You **assume full responsibility** for any investment decisions taken based on this analysis.

3. thealphalens.com, its owners, developers, and affiliates **shall not be held liable** for any direct or indirect losses, damages, or consequences arising from actions taken based on these recommendations, at any present or future date.

---

**Professional Consultation Recommended:**

You are strongly advised to **consult a qualified, SEBI-registered investment advisor, research analyst, or financial professional** before making any investment, trading, or portfolio rebalancing decisions.
        """)
    
    st.markdown("")
    
    agree_checkbox = st.checkbox(
        "I have read and understood the above disclaimer. I acknowledge the risks involved and accept full responsibility for my investment decisions.",
        key=f"disclaimer_checkbox_{section_type}"
    )
    
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        btn_label = "I Agree - View Investment Advice" if section_type == 'advice' else "I Agree - View Rebalancing Suggestions"
        if agree_checkbox:
            if st.button(btn_label, type="primary", use_container_width=True, key=f"agree_btn_{section_type}"):
                st.session_state.disclaimer_accepted = True
                st.rerun()
        else:
            st.button("Please check the box above to proceed", disabled=True, use_container_width=True, key=f"disabled_btn_{section_type}")

def main():
    st.set_page_config(
        page_title="Alphalens Portfolio Analyzer",
        page_icon="attached_assets/Screenshot_2026-01-29_at_5.07.59_PM-removebg-preview_1769686716431.png",
        layout="wide",
        initial_sidebar_state="collapsed"
    )
    
    if 'db_initialized' not in st.session_state:
        st.session_state.db_initialized = init_database()
    
    st.markdown("""
    <style>
        /* Hide all Streamlit branding and elements */
        [data-testid="stStatusWidget"] {
            display: none !important;
        }
        header[data-testid="stHeader"] {
            display: none !important;
        }
        #MainMenu {
            visibility: hidden !important;
        }
        footer {
            visibility: hidden !important;
        }
        .stDeployButton {
            display: none !important;
        }
        /* Hide Made with Streamlit */
        .viewerBadge_container__1QSob,
        .viewerBadge_link__1S137,
        [data-testid="stToolbar"],
        [data-testid="stDecoration"],
        .stApp > header,
        #stDecoration,
        .streamlit-footer {
            display: none !important;
            visibility: hidden !important;
        }
        /* Remove Streamlit watermark */
        .reportview-container .main footer,
        footer::after {
            display: none !important;
            content: none !important;
        }
        /* Hide loading spinner, running indicator, and Streamlit logo */
        .stSpinner, 
        [data-testid="stSpinner"],
        .st-emotion-cache-1dp5vir,
        div[data-testid="stStatusWidget"],
        .stApp [data-testid="stDecoration"],
        .stDeployButton,
        button[kind="header"],
        [data-testid="stLogoImprovedImage"],
        [data-testid="stLogo"],
        img[alt="Streamlit logo"],
        .st-emotion-cache-h5rgaw,
        .st-emotion-cache-1avcm0n,
        div[data-testid="stImage"] img[src*="streamlit"] {
            display: none !important;
            visibility: hidden !important;
            opacity: 0 !important;
        }
        /* Hide hamburger menu */
        button[kind="header"],
        .st-emotion-cache-eczf16 {
            display: none !important;
        }
        /* Hide loading screen logo */
        [data-testid="stAppViewBlockContainer"] > [data-testid="stVerticalBlock"]:first-child::before {
            display: none !important;
        }
        /* Hide Streamlit loading animation and logo on page load */
        [data-testid="stAppLoadingIndicator"],
        .stProgress,
        div[class*="stSpinner"],
        div[class*="stLoader"],
        .st-emotion-cache-z5fcl4,
        [data-testid="stMarkdownContainer"] img[src*="streamlit"],
        [data-testid="stImage"] img[src*="streamlit"],
        img[alt*="Streamlit"],
        div[data-testid="stStatusWidget"] {
            display: none !important;
            visibility: hidden !important;
        }
        /* Override any Streamlit logo in header */
        .stApp header img,
        header[data-testid="stHeader"] img {
            display: none !important;
        }
        
        /* Main container with proper margins */
        .block-container {
            padding-top: 1rem;
            padding-bottom: 2rem;
            padding-left: 4rem !important;
            padding-right: 4rem !important;
            max-width: 1400px !important;
            margin: 0 auto !important;
        }
        h2, h3 {
            margin-top: 0.5rem !important;
            margin-bottom: 0.5rem !important;
        }
        .content-section {
            padding-left: 2rem;
            padding-right: 2rem;
        }
        .auth-container {
            max-width: 400px;
            margin: 0 auto;
            padding: 2rem;
            background: #f8f9fa;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .auth-header {
            text-align: center;
            color: #FF6B35;
            margin-bottom: 1.5rem;
        }
    </style>
    """, unsafe_allow_html=True)
    
    if 'authenticated' not in st.session_state:
        st.session_state.authenticated = False
    if 'user' not in st.session_state:
        st.session_state.user = None
    if 'portfolio_data' not in st.session_state:
        st.session_state.portfolio_data = None
    if 'analysis_complete' not in st.session_state:
        st.session_state.analysis_complete = False
    if 'show_login' not in st.session_state:
        st.session_state.show_login = False
    if 'show_signup' not in st.session_state:
        st.session_state.show_signup = False
    if 'show_admin' not in st.session_state:
        st.session_state.show_admin = False
    if 'nav_section' not in st.session_state:
        st.session_state.nav_section = None
    if 'uploaded_file_name' not in st.session_state:
        st.session_state.uploaded_file_name = None
    if 'show_subscription' not in st.session_state:
        st.session_state.show_subscription = False
    if 'razorpay_order' not in st.session_state:
        st.session_state.razorpay_order = None
    if 'show_upload_page' not in st.session_state:
        st.session_state.show_upload_page = False
    
    if st.session_state.show_subscription and st.session_state.authenticated:
        display_subscription_page()
    elif st.session_state.show_admin and st.session_state.authenticated and st.session_state.user.get('is_admin'):
        display_admin_panel()
    elif st.session_state.portfolio_data is not None and st.session_state.analysis_complete:
        display_analysis()
    elif st.session_state.portfolio_data is not None:
        display_portfolio_preview()
    elif st.session_state.authenticated and st.session_state.show_upload_page:
        display_upload_page()
    else:
        display_welcome_screen()
    
    add_footer()

def render_top_header():
    """Render top header with logo, navigation menu, and auth buttons - thealphamarket style"""
    
    st.markdown("""
    <style>
        /* Main page background stays white */
        .stApp {
            background: white !important;
        }
        /* Style the menu container */
        div[data-testid="stVerticalBlockBorderWrapper"]:has(> div > div > div[data-testid="stVerticalBlock"] > div[data-testid="stHorizontalBlock"]) {
            background: linear-gradient(90deg, #fff8f5 0%, #ffede6 100%) !important;
            border-radius: 50px !important;
            border: none !important;
            padding: 8px 20px !important;
            margin-bottom: 20px !important;
        }
        /* Style buttons with rounded corners */
        div[data-testid="stVerticalBlockBorderWrapper"] button {
            border-radius: 20px !important;
            font-size: 14px !important;
        }
        /* Nav buttons - transparent with border */
        .nav-section button {
            background: transparent !important;
            border: 1px solid #ddd !important;
            color: #333 !important;
        }
        /* CTA button - coral */
        .cta-section button {
            background: #e8734a !important;
            border: none !important;
            color: white !important;
        }
        /* Register button - coral */
        .register-section button {
            background: #e8734a !important;
            border: none !important;
            color: white !important;
        }
        /* Login button - green */
        .login-section button {
            background: #27ae60 !important;
            border: none !important;
            color: white !important;
        }
    </style>
    """, unsafe_allow_html=True)
    
    with st.container(border=True):
        col_logo, col_nav, col_cta, col_auth = st.columns([1.0, 4.2, 1.2, 1.6])
        
        with col_logo:
            st.markdown("""
            <div style="padding: 5px 0; font-size: 26px; font-weight: 700; color: #333;">
                <span style="color: #e74c3c;">α</span>lphalens
            </div>
            """, unsafe_allow_html=True)
        
        with col_nav:
            n1, n2, n3, n4 = st.columns([1, 1.3, 1, 1.2])
            with n1:
                if st.button("Features", key="nav_features", use_container_width=True):
                    st.session_state.nav_section = "features"
                    st.rerun()
            with n2:
                if st.button("Methodology", key="nav_methodology", use_container_width=True):
                    st.session_state.nav_section = "methodology"
                    st.rerun()
            with n3:
                if st.button("About", key="nav_about", use_container_width=True):
                    st.session_state.nav_section = "about"
                    st.rerun()
            with n4:
                if st.button("Partnership", key="nav_partner", use_container_width=True):
                    st.session_state.nav_section = "partner"
                    st.rerun()
        
        with col_cta:
            if st.button("Analyze Portfolio", key="cta_analyze", use_container_width=True, type="primary"):
                if st.session_state.authenticated:
                    st.session_state.show_upload_page = True
                    st.rerun()
                else:
                    st.session_state.show_login = True
                    st.rerun()
        
        with col_auth:
            if st.session_state.authenticated:
                user_name = st.session_state.user.get('full_name') or st.session_state.user.get('email', 'User')
                c1, c2 = st.columns([1.2, 1])
                with c1:
                    st.markdown(f"""
                    <div style="color: #27ae60; font-weight: 600; font-size: 13px; padding-top: 10px; text-align: center;">
                        ✅ {user_name[:10]}
                    </div>
                    """, unsafe_allow_html=True)
                with c2:
                    if st.button("Logout", key="logout_top", use_container_width=True):
                        st.session_state.authenticated = False
                        st.session_state.user = None
                        st.session_state.portfolio_data = None
                        st.session_state.analysis_complete = False
                        st.session_state.show_admin = False
                        st.session_state.show_subscription = False
                        st.rerun()
            else:
                c1, c2 = st.columns(2)
                with c1:
                    if st.button("Register", key="register_top", use_container_width=True, type="primary"):
                        st.session_state.show_signup = True
                        st.rerun()
                with c2:
                    if st.button("Login", key="login_top", use_container_width=True):
                        st.session_state.show_login = True
                        st.rerun()

def render_auth_header():
    with st.sidebar:
        st.image("attached_assets/AlphaMarket_(2)_1767079367380.png", width=250)
        st.markdown("---")
        
        if st.session_state.authenticated:
            user_name = st.session_state.user.get('full_name') or st.session_state.user.get('email', 'User')
            st.success(f"✅ Logged in as **{user_name[:20]}**")
            
            if st.button("💎 Premium", key="premium_btn", use_container_width=True):
                st.session_state.show_subscription = True
                st.session_state.show_admin = False
                st.rerun()
            
            if st.session_state.user.get('is_admin'):
                if st.button("📊 Admin Panel", key="admin_btn", use_container_width=True):
                    st.session_state.show_admin = True
                    st.session_state.show_subscription = False
                    st.rerun()
            
            if st.button("🚪 Logout", key="logout_btn", use_container_width=True):
                st.session_state.authenticated = False
                st.session_state.user = None
                st.session_state.portfolio_data = None
                st.session_state.analysis_complete = False
                st.session_state.show_admin = False
                st.rerun()
        else:
            st.markdown("""
            <div style='background: linear-gradient(135deg, #FF6B35 0%, #ff8c5a 100%); padding: 15px; border-radius: 10px; text-align: center; margin-bottom: 15px;'>
                <h3 style='color: white; margin: 0 0 10px 0;'>🔐 Sign In Required</h3>
                <p style='color: white; font-size: 13px; margin: 0;'>Login or Register to analyze your portfolio</p>
            </div>
            """, unsafe_allow_html=True)
            
            if st.button("🔐 LOGIN", key="login_btn", use_container_width=True, type="primary"):
                st.session_state.show_login = True
                st.rerun()
            
            if st.button("📝 CREATE ACCOUNT", key="register_btn", use_container_width=True):
                st.session_state.show_signup = True
                st.rerun()
        
        st.markdown("---")

def display_login_modal():
    st.markdown("---")
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        st.markdown("""
        <div style='background: #fff5f2; padding: 20px; border-radius: 10px; border: 2px solid #FF6B35;'>
        <h3 style='color: #FF6B35; text-align: center;'>Login to Your Account</h3>
        </div>
        """, unsafe_allow_html=True)
        
        with st.form("login_form"):
            login_email = st.text_input("Email", placeholder="Enter your email")
            login_password = st.text_input("Password", type="password", placeholder="Enter your password")
            
            col_a, col_b = st.columns(2)
            with col_a:
                login_submitted = st.form_submit_button("Login", type="primary", use_container_width=True)
            with col_b:
                cancel = st.form_submit_button("Cancel", use_container_width=True)
            
            if cancel:
                st.session_state.show_login = False
                st.rerun()
            
            if login_submitted:
                if login_email and login_password:
                    try:
                        from utils.auth import AuthManager
                        auth = AuthManager()
                        result = auth.login(login_email, login_password)
                        
                        if result['success']:
                            st.session_state.authenticated = True
                            st.session_state.user = {
                                'id': result['user_id'],
                                'email': result['email'],
                                'full_name': result.get('full_name', ''),
                                'is_admin': result.get('is_admin', False)
                            }
                            st.session_state.show_login = False
                            st.session_state.show_upload_page = True
                            st.success("Login successful!")
                            st.rerun()
                        else:
                            st.error(result['message'])
                    except Exception as e:
                        st.error(f"Login error: {str(e)}")
                else:
                    st.warning("Please enter both email and password")

def display_signup_modal():
    st.markdown("---")
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        st.markdown("""
        <div style='background: #fff5f2; padding: 20px; border-radius: 10px; border: 2px solid #FF6B35;'>
        <h3 style='color: #FF6B35; text-align: center;'>Create Your Account</h3>
        </div>
        """, unsafe_allow_html=True)
        
        with st.form("signup_form"):
            signup_name = st.text_input("Full Name", placeholder="Enter your full name")
            signup_email = st.text_input("Email", placeholder="Enter your email")
            signup_phone = st.text_input("Phone (optional)", placeholder="Enter your phone number")
            signup_password = st.text_input("Password", type="password", placeholder="Create a password (min 6 characters)")
            signup_confirm = st.text_input("Confirm Password", type="password", placeholder="Confirm your password")
            
            col_a, col_b = st.columns(2)
            with col_a:
                signup_submitted = st.form_submit_button("Create Account", type="primary", use_container_width=True)
            with col_b:
                cancel = st.form_submit_button("Cancel", use_container_width=True)
            
            if cancel:
                st.session_state.show_signup = False
                st.rerun()
            
            if signup_submitted:
                if not signup_email or not signup_password:
                    st.warning("Please enter email and password")
                elif len(signup_password) < 6:
                    st.warning("Password must be at least 6 characters")
                elif signup_password != signup_confirm:
                    st.error("Passwords do not match")
                else:
                    try:
                        from utils.auth import AuthManager
                        auth = AuthManager()
                        result = auth.signup(signup_email, signup_password, signup_name, signup_phone)
                        
                        if result['success']:
                            st.session_state.authenticated = True
                            st.session_state.user = {
                                'id': result['user_id'],
                                'email': result['email'],
                                'full_name': result.get('full_name', ''),
                                'is_admin': False
                            }
                            st.session_state.show_signup = False
                            st.session_state.show_upload_page = True
                            st.success("Account created successfully!")
                            st.rerun()
                        else:
                            st.error(result['message'])
                    except Exception as e:
                        st.error(f"Registration error: {str(e)}")

def display_subscription_page():
    """Display subscription/payment page with Razorpay integration"""
    render_auth_header()
    
    st.markdown("""
    <div style='background: linear-gradient(135deg, #e31837 0%, #ff4d5a 100%); padding: 30px; border-radius: 15px; margin: 20px 5rem; text-align: center;'>
        <h1 style='color: white; margin: 0; font-size: 36px;'>Upgrade to Premium</h1>
        <p style='color: rgba(255,255,255,0.9); margin-top: 10px; font-size: 18px;'>Unlock unlimited portfolio analysis and advanced features</p>
    </div>
    """, unsafe_allow_html=True)
    
    col1, col2 = st.columns([1, 4])
    with col1:
        if st.button("← Back to Home", use_container_width=True):
            st.session_state.show_subscription = False
            st.rerun()
    
    from utils.database import Database
    db = Database()
    
    user_id = st.session_state.user.get('id')
    active_sub = db.get_active_subscription(user_id)
    
    if active_sub:
        st.markdown("""
        <div style='background: #d4edda; border: 1px solid #28a745; border-radius: 10px; padding: 30px; margin: 20px 5rem; text-align: center;'>
            <h2 style='color: #155724; margin-bottom: 10px;'>✅ You have an active subscription!</h2>
            <p style='color: #155724; font-size: 16px; margin: 0;'>Your premium access is valid until <strong>{}</strong></p>
        </div>
        """.format(active_sub['end_date'].strftime('%B %d, %Y') if active_sub['end_date'] else 'N/A'), unsafe_allow_html=True)
        return
    
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        st.markdown("""
        <div style='background: white; border: 2px solid #e31837; border-radius: 15px; padding: 40px; text-align: center; box-shadow: 0 10px 30px rgba(0,0,0,0.1);'>
            <div style='background: #e31837; color: white; padding: 5px 15px; border-radius: 20px; display: inline-block; margin-bottom: 20px; font-size: 14px; font-weight: 600;'>MOST POPULAR</div>
            <h2 style='color: #1a1a1a; font-size: 28px; margin-bottom: 10px;'>Monthly Premium</h2>
            <div style='margin: 20px 0;'>
                <span style='color: #888; font-size: 18px; text-decoration: line-through;'>₹999/month</span>
                <div style='color: #e31837; font-size: 48px; font-weight: 800; margin: 10px 0;'>₹499<span style='font-size: 18px; font-weight: 400;'>/month</span></div>
                <span style='background: #fff3cd; color: #856404; padding: 5px 15px; border-radius: 15px; font-size: 14px;'>Save ₹500!</span>
            </div>
            <hr style='margin: 25px 0; border: 0; border-top: 1px solid #eee;'>
            <div style='text-align: left; padding: 0 20px;'>
                <p style='color: #333; margin: 10px 0; font-size: 15px;'>✅ Unlimited portfolio analyses</p>
                <p style='color: #333; margin: 10px 0; font-size: 15px;'>✅ Advanced expert recommendations</p>
                <p style='color: #333; margin: 10px 0; font-size: 15px;'>✅ Sector-wise allocation insights</p>
                <p style='color: #333; margin: 10px 0; font-size: 15px;'>✅ Benchmark comparisons (NIFTY 50, Sensex)</p>
                <p style='color: #333; margin: 10px 0; font-size: 15px;'>✅ PDF report downloads</p>
                <p style='color: #333; margin: 10px 0; font-size: 15px;'>✅ Portfolio rebalancing suggestions</p>
                <p style='color: #333; margin: 10px 0; font-size: 15px;'>✅ Historical performance tracking</p>
                <p style='color: #333; margin: 10px 0; font-size: 15px;'>✅ Priority customer support</p>
            </div>
        </div>
        """, unsafe_allow_html=True)
        
        st.markdown("<br>", unsafe_allow_html=True)
        
        import os
        razorpay_key_id = os.environ.get('RAZORPAY_KEY_ID')
        
        if razorpay_key_id:
            if st.button("💳 Subscribe Now - ₹499/month", type="primary", use_container_width=True):
                from utils.razorpay_client import create_order
                order = create_order(amount=49900, receipt=f"user_{user_id}_{datetime.now().strftime('%Y%m%d%H%M%S')}")
                
                if order and 'error' not in order:
                    st.session_state.razorpay_order = order
                    db.create_subscription(user_id, order['id'], 49900, 'monthly')
                    
                    checkout_html = f"""
                    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
                    <script>
                    var options = {{
                        "key": "{razorpay_key_id}",
                        "amount": "49900",
                        "currency": "INR",
                        "name": "Alphalens",
                        "description": "Monthly Premium Subscription",
                        "order_id": "{order['id']}",
                        "prefill": {{
                            "name": "{st.session_state.user.get('full_name', '')}",
                            "email": "{st.session_state.user.get('email', '')}",
                            "contact": ""
                        }},
                        "theme": {{
                            "color": "#e31837"
                        }},
                        "handler": function (response){{
                            window.parent.postMessage({{
                                type: 'razorpay_success',
                                payment_id: response.razorpay_payment_id,
                                order_id: response.razorpay_order_id,
                                signature: response.razorpay_signature
                            }}, '*');
                            alert('Payment Successful! Your subscription is now active. Please refresh the page.');
                        }}
                    }};
                    var rzp1 = new Razorpay(options);
                    rzp1.on('payment.failed', function (response){{
                        alert('Payment failed. Please try again.');
                    }});
                    rzp1.open();
                    </script>
                    """
                    st.components.v1.html(checkout_html, height=0)
                elif order and 'error' in order:
                    st.error(f"Payment gateway error: {order['error']}. Please contact support.")
                else:
                    st.error("Failed to create payment order. Please check Razorpay API keys.")
            
            payment_id = st.text_input("Enter Payment ID (after successful payment):", key="payment_verification")
            if payment_id and st.button("Verify Payment", use_container_width=True):
                if st.session_state.razorpay_order:
                    from utils.razorpay_client import get_payment_details
                    payment = get_payment_details(payment_id)
                    if payment and payment.get('status') == 'captured':
                        db.update_subscription_payment(
                            st.session_state.razorpay_order['id'],
                            payment_id,
                            ''
                        )
                        st.success("Payment verified! Your subscription is now active.")
                        st.session_state.razorpay_order = None
                        st.rerun()
                    else:
                        st.error("Payment verification failed. Please contact support.")
        else:
            st.warning("Payment gateway is being configured. Please check back later.")
        
        st.markdown("""
        <div style='text-align: center; margin-top: 20px; padding: 15px; background: #f8f9fa; border-radius: 10px;'>
            <p style='color: #666; font-size: 13px; margin: 0;'>🔒 Secure payment powered by Razorpay</p>
            <p style='color: #888; font-size: 12px; margin-top: 5px;'>Cancel anytime. No questions asked.</p>
        </div>
        """, unsafe_allow_html=True)

def display_admin_panel():
    render_auth_header()
    
    st.markdown("""
    <div style='background: linear-gradient(135deg, #FF6B35 0%, #ff8c5a 100%); padding: 20px; border-radius: 10px; margin: 20px 0;'>
        <h2 style='color: white; text-align: center; margin: 0;'>Admin Dashboard</h2>
    </div>
    """, unsafe_allow_html=True)
    
    col1, col2 = st.columns([1, 4])
    with col1:
        if st.button("← Back to Home", use_container_width=True):
            st.session_state.show_admin = False
            st.rerun()
    
    try:
        from utils.database import Database
        db = Database()
        
        stats = db.get_admin_stats()
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Total Users", stats['total_users'])
        with col2:
            st.metric("Total Analyses", stats['total_analyses'])
        with col3:
            st.metric("Active Users", stats['active_users'])
        
        st.markdown("---")
        
        tab1, tab2, tab3 = st.tabs(["Users", "Portfolio History", "Activity Log"])
        
        with tab1:
            st.subheader("Registered Users")
            users = db.get_all_users()
            if users:
                users_df = pd.DataFrame(users)
                users_df['created_at'] = pd.to_datetime(users_df['created_at']).dt.strftime('%Y-%m-%d %H:%M')
                users_df['last_login'] = pd.to_datetime(users_df['last_login']).dt.strftime('%Y-%m-%d %H:%M')
                st.dataframe(users_df[['email', 'full_name', 'phone', 'is_admin', 'created_at', 'last_login']], use_container_width=True)
            else:
                st.info("No users registered yet")
        
        with tab2:
            st.subheader("Portfolio Evaluations")
            portfolios = db.get_all_portfolio_history()
            if portfolios:
                portfolios_df = pd.DataFrame(portfolios)
                portfolios_df['created_at'] = pd.to_datetime(portfolios_df['created_at']).dt.strftime('%Y-%m-%d %H:%M')
                portfolios_df['total_investment'] = portfolios_df['total_investment'].apply(lambda x: f"₹{float(x):,.2f}" if x else "N/A")
                portfolios_df['current_value'] = portfolios_df['current_value'].apply(lambda x: f"₹{float(x):,.2f}" if x else "N/A")
                portfolios_df['total_gain_loss'] = portfolios_df['total_gain_loss'].apply(lambda x: f"₹{float(x):,.2f}" if x else "N/A")
                st.dataframe(portfolios_df[['email', 'full_name', 'file_name', 'stock_count', 'total_investment', 'current_value', 'total_gain_loss', 'created_at']], use_container_width=True)
            else:
                st.info("No portfolio analyses recorded yet")
        
        with tab3:
            st.subheader("User Activity Log")
            activities = db.get_user_activity(50)
            if activities:
                activities_df = pd.DataFrame(activities)
                activities_df['created_at'] = pd.to_datetime(activities_df['created_at']).dt.strftime('%Y-%m-%d %H:%M')
                st.dataframe(activities_df[['email', 'activity_type', 'details', 'created_at']], use_container_width=True)
            else:
                st.info("No activity recorded yet")
    except Exception as e:
        st.error(f"Error loading admin data: {str(e)}")

def analyze_portfolio():
    """Perform comprehensive portfolio analysis"""
    try:
        portfolio_df = st.session_state.portfolio_data
        
        # Initialize analyzers
        data_fetcher = DataFetcher()
        portfolio_analyzer = PortfolioAnalyzer()
        recommendation_engine = RecommendationEngine()
        
        # Fetch current market data
        progress_bar = st.progress(0)
        st.text("Fetching current stock prices...")
        
        current_data = {}
        historical_data = {}
        
        for idx, (_, stock) in enumerate(portfolio_df.iterrows()):
            stock_name = stock['Stock Name']
            buy_date = stock['Buy Date']
            
            # Fetch current price and historical data
            current_price, hist_data = data_fetcher.get_stock_data(stock_name, buy_date)
            
            # Only add to current_data if price was successfully fetched
            if current_price is not None:
                current_data[stock_name] = current_price
                historical_data[stock_name] = hist_data
            else:
                st.error(f"⚠️ Skipping {stock_name} due to data fetch failure")
            
            progress_bar.progress((idx + 1) / len(portfolio_df))
        
        st.text("Analyzing portfolio performance...")
        
        # Perform analysis
        analysis_results = portfolio_analyzer.analyze_portfolio(
            portfolio_df, current_data, historical_data
        )
        
        # Create enriched portfolio DataFrame from analysis results
        enriched_portfolio_df = pd.DataFrame(analysis_results['stock_performance'])
        
        # Generate recommendations using enriched data
        recommendations = recommendation_engine.generate_recommendations(
            enriched_portfolio_df, current_data, historical_data, analysis_results
        )
        
        # Store results in session state
        st.session_state.analysis_results = analysis_results
        st.session_state.recommendations = recommendations
        st.session_state.current_data = current_data
        st.session_state.historical_data = historical_data
        st.session_state.analysis_complete = True
        
        if 'advanced_metrics' in st.session_state:
            del st.session_state.advanced_metrics
        
        progress_bar.progress(1.0)
        st.success("Analysis complete!")
        
        try:
            from utils.database import Database
            db = Database()
            user_id = st.session_state.user.get('id') if st.session_state.user else None
            if user_id:
                file_name = st.session_state.get('uploaded_file_name', 'Unknown')
                stock_count = len(portfolio_df)
                total_investment = analysis_results.get('total_investment', 0)
                current_value = analysis_results.get('current_value', 0)
                total_gain_loss = analysis_results.get('total_gain_loss', 0)
                
                stocks_list = [{'name': stock['Stock Name'], 'qty': int(stock['Quantity'])} 
                              for _, stock in portfolio_df.iterrows()]
                
                db.save_portfolio_history(
                    user_id, file_name, stock_count, total_investment,
                    current_value, total_gain_loss, stocks_list
                )
                db.log_activity(user_id, 'portfolio_analysis', f'Analyzed {stock_count} stocks')
        except Exception as e:
            pass
        
        # Auto-rerun to display results
        st.rerun()
        
    except Exception as e:
        st.error(f"Error during analysis: {str(e)}")
        st.session_state.analysis_complete = False

def refresh_prices():
    """Refresh stock prices with latest market data"""
    try:
        portfolio_df = st.session_state.portfolio_data
        data_fetcher = DataFetcher()
        portfolio_analyzer = PortfolioAnalyzer()
        recommendation_engine = RecommendationEngine()
        
        # Fetch updated prices
        current_data = {}
        historical_data = st.session_state.historical_data  # Keep existing historical data
        
        for _, stock in portfolio_df.iterrows():
            stock_name = stock['Stock Name']
            buy_date = stock['Buy Date']
            
            # Fetch current price only
            current_price, _ = data_fetcher.get_stock_data(stock_name, buy_date)
            
            # Only add if price was successfully fetched
            if current_price is not None:
                current_data[stock_name] = current_price
        
        # Re-analyze with updated prices
        analysis_results = portfolio_analyzer.analyze_portfolio(
            portfolio_df, current_data, historical_data
        )
        
        # Create enriched portfolio DataFrame from analysis results
        enriched_portfolio_df = pd.DataFrame(analysis_results['stock_performance'])
        
        recommendations = recommendation_engine.generate_recommendations(
            enriched_portfolio_df, current_data, historical_data, analysis_results
        )
        
        # Update session state
        st.session_state.current_data = current_data
        st.session_state.analysis_results = analysis_results
        st.session_state.recommendations = recommendations
        
        if 'advanced_metrics' in st.session_state:
            del st.session_state.advanced_metrics
        
        st.success("Prices updated successfully!")
        st.rerun()
        
    except Exception as e:
        st.error(f"Error refreshing prices: {str(e)}")

def display_analysis():
    """Display comprehensive portfolio analysis"""
    
    render_auth_header()
    
    # Apply global styling for margins and card-based sections
    st.markdown("""
    <style>
    /* Add margins to main container */
    .main .block-container {
        padding-left: 3rem !important;
        padding-right: 3rem !important;
        padding-bottom: 3rem !important;
        max-width: 1400px !important;
    }
    
    /* Style for section cards */
    .section-card {
        background-color: #ffffff;
        border: 1px solid #e0e0e0;
        border-radius: 10px;
        padding: 25px;
        margin-bottom: 20px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.08);
    }
    
    /* Header card styling */
    .header-card {
        background: linear-gradient(135deg, #fff5f2 0%, #ffffff 100%);
        border: 2px solid #FF6B35;
        border-radius: 12px;
        padding: 30px;
        margin-bottom: 25px;
        box-shadow: 0 4px 8px rgba(255, 107, 53, 0.1);
    }
    
    /* Tab content styling */
    div[data-testid="stTabs"] > div {
        background-color: #ffffff;
        border: 1px solid #e0e0e0;
        border-radius: 10px;
        padding: 20px;
        margin-top: 15px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
    }
    </style>
    """, unsafe_allow_html=True)
    
    # Professional header with card styling
    st.markdown("""
    <div class="header-card">
        <div style='text-align: center;'>
            <h1 style='color: #FF6B35; margin-bottom: 10px; font-size: 32px; font-weight: 600;'>📊 Portfolio Analysis Report</h1>
            <p style='color: #666; font-size: 16px; margin-bottom: 0;'>Comprehensive analysis of your investment portfolio</p>
        </div>
    </div>
    """, unsafe_allow_html=True)
    
    st.markdown('<div class="section-card">', unsafe_allow_html=True)
    
    # User info and logout row
    info_col, logout_col = st.columns([6, 1])
    with info_col:
        user_name = ""
        if st.session_state.user:
            user_name = st.session_state.user.get('full_name') or st.session_state.user.get('email', '')
        st.markdown(f"**📅 Analysis Date:** {datetime.now().strftime('%B %d, %Y at %I:%M %p')} | **User:** {user_name}")
    with logout_col:
        if st.button("🚪 Logout", key="logout_analysis", help="Sign out"):
            st.session_state.authenticated = False
            st.session_state.user = None
            st.session_state.portfolio_data = None
            st.session_state.analysis_complete = False
            st.rerun()
    
    # Action buttons row with AI Assistant prominently placed
    col1, col2, col3, col4 = st.columns([1, 1.2, 1, 1.2])
    
    with col1:
        if st.button("🔄 Refresh Prices", type="secondary", help="Update with latest stock prices", use_container_width=True):
            with st.spinner("Refreshing prices..."):
                refresh_prices()
    
    with col2:
        # Generate PDF report
        if st.button("📄 Download Report", type="primary", help="Generate comprehensive PDF report", use_container_width=True):
            with st.spinner("Generating PDF report..."):
                try:
                    pdf_gen = PDFReportGenerator()
                    filename = f"portfolio_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
                    pdf_gen.generate_report(
                        st.session_state.analysis_results,
                        st.session_state.portfolio_data,
                        st.session_state.recommendations,
                        filename,
                        st.session_state.historical_data,
                        st.session_state.current_data
                    )
                    
                    # Read the generated PDF
                    with open(filename, "rb") as pdf_file:
                        pdf_bytes = pdf_file.read()
                    
                    st.download_button(
                        label="⬇️ Download PDF",
                        data=pdf_bytes,
                        file_name=filename,
                        mime="application/pdf"
                    )
                    st.success("PDF report generated successfully!")
                except Exception as e:
                    st.error(f"Error generating PDF: {str(e)}")
    
    with col3:
        if st.button("🏠 New Analysis", type="secondary", help="Start a new portfolio analysis", use_container_width=True):
            st.session_state.portfolio_data = None
            st.session_state.analysis_complete = False
            st.rerun()
    
    with col4:
        # AI Assistant button - prominent placement
        st.markdown("""
        <style>
        div[data-testid="stButton"] button[kind="primary"]:has(span:contains("AI Assistant")) {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%) !important;
        }
        </style>
        """, unsafe_allow_html=True)
        if st.button("✨ Portfolio Advisor", type="primary", help="Get expert insights about your portfolio", use_container_width=True):
            st.session_state.show_ai_assistant = True
            st.rerun()
    
    st.markdown('</div>', unsafe_allow_html=True)
    
    # Show AI Assistant modal if triggered
    if st.session_state.get('show_ai_assistant', False):
        render_ai_assistant_modal()
    
    # Add CSS to make tabs scrollable and compact
    st.markdown("""
    <style>
    /* Make tabs container scrollable */
    .stTabs [data-baseweb="tab-list"] {
        gap: 4px;
        overflow-x: auto;
        flex-wrap: nowrap;
    }
    /* Compact tab styling */
    .stTabs [data-baseweb="tab"] {
        padding: 8px 12px;
        font-size: 13px;
        white-space: nowrap;
    }
    </style>
    """, unsafe_allow_html=True)
    
    # Create tabs for different analysis sections
    tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8, tab9, tab10 = st.tabs([
        "📊 Dashboard", 
        "🏭 Sectors", 
        "📈 Stocks", 
        "📊 Benchmark", 
        "💡 Advice",
        "⚖️ Rebalance",
        "📅 History",
        "👤 Profile",
        "🔬 Advanced",
        "📐 Methodology"
    ])
    
    with tab1:
        dashboard = Dashboard()
        dashboard.render(
            st.session_state.analysis_results,
            st.session_state.portfolio_data,
            st.session_state.current_data
        )
    
    with tab2:
        sector_analysis = SectorAnalysis()
        sector_analysis.render(
            st.session_state.analysis_results,
            st.session_state.portfolio_data
        )
    
    with tab3:
        stock_performance = StockPerformance()
        stock_performance.render(
            st.session_state.analysis_results,
            st.session_state.portfolio_data,
            st.session_state.current_data,
            st.session_state.historical_data
        )
    
    with tab4:
        benchmark_comparison = BenchmarkComparison()
        benchmark_comparison.render(
            st.session_state.analysis_results,
            st.session_state.portfolio_data
        )
    
    with tab5:
        if st.session_state.get('disclaimer_accepted', False):
            recommendations = Recommendations()
            recommendations.render(
                st.session_state.recommendations,
                st.session_state.analysis_results
            )
        else:
            render_disclaimer_overlay('advice')
    
    with tab6:
        if st.session_state.get('disclaimer_accepted', False):
            rebalancing = PortfolioRebalancing()
            rebalancing.render(
                st.session_state.analysis_results,
                st.session_state.portfolio_data,
                st.session_state.current_data
            )
        else:
            render_disclaimer_overlay('rebalance')
    
    with tab7:
        historical_performance = HistoricalPerformance()
        historical_performance.render(
            st.session_state.analysis_results,
            st.session_state.portfolio_data,
            st.session_state.historical_data
        )
    
    with tab8:
        customer_profile = CustomerProfile()
        customer_profile.render(
            st.session_state.analysis_results,
            st.session_state.portfolio_data,
            st.session_state.recommendations
        )
    
    with tab9:
        if 'advanced_metrics' not in st.session_state:
            with st.spinner("Calculating advanced metrics..."):
                metrics_calculator = AdvancedMetricsCalculator()
                
                stock_perf = st.session_state.analysis_results.get('stock_performance', [])
                portfolio_for_metrics = pd.DataFrame(stock_perf)
                
                benchmark_data = None
                if 'NIFTY 50' in st.session_state.historical_data:
                    benchmark_data = st.session_state.historical_data['NIFTY 50']
                
                st.session_state.advanced_metrics = metrics_calculator.calculate_all_metrics(
                    portfolio_for_metrics,
                    st.session_state.historical_data,
                    benchmark_data
                )
        
        render_advanced_metrics_tab(st.session_state.advanced_metrics)
    
    with tab10:
        from components.methodology import Methodology
        methodology = Methodology()
        methodology.render()

@st.dialog("✨ Alphalens Portfolio Advisor", width="large")
def render_ai_assistant_modal():
    """Render the Portfolio Advisor as a modal dialog"""
    from utils.ai_assistant import chat_with_assistant
    
    st.markdown("""
    <div style='background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 15px 20px; border-radius: 10px; margin-bottom: 15px;'>
        <p style='color: white; margin: 0; font-size: 16px;'>Ask me anything about your portfolio - performance, recommendations, sector allocation, and more!</p>
    </div>
    """, unsafe_allow_html=True)
    
    if 'ai_chat_history' not in st.session_state:
        st.session_state.ai_chat_history = []
    
    # Chat history display
    chat_container = st.container(height=350)
    with chat_container:
        if not st.session_state.ai_chat_history:
            st.markdown("""
            <div style='background: #f8f9fa; padding: 15px; border-radius: 8px; text-align: center;'>
                <p style='color: #666; margin: 0 0 10px 0;'>👋 Hello! I'm your portfolio advisor.</p>
                <p style='color: #888; font-size: 13px; margin: 0;'>Try: "How is my portfolio doing?" or "Which stocks should I sell?"</p>
            </div>
            """, unsafe_allow_html=True)
        else:
            for msg in st.session_state.ai_chat_history:
                if msg["role"] == "user":
                    st.markdown(f"""
                    <div style='background: #e3f2fd; padding: 10px 12px; border-radius: 12px 12px 4px 12px; margin: 8px 0; margin-left: 15%;'>
                        <strong>You:</strong> {msg["content"]}
                    </div>
                    """, unsafe_allow_html=True)
                else:
                    st.markdown(f"""
                    <div style='background: #f5f5f5; padding: 10px 12px; border-radius: 12px 12px 12px 4px; margin: 8px 0; margin-right: 10%;'>
                        <strong>✨ Advisor:</strong> {msg["content"]}
                    </div>
                    """, unsafe_allow_html=True)
    
    # Quick questions
    st.markdown("**💡 Quick Questions:**")
    qcol1, qcol2, qcol3 = st.columns(3)
    quick_questions = [
        ("Portfolio performance", "How is my portfolio performing?"),
        ("Top performers", "Which are my best performing stocks?"),
        ("Recommendations", "What stocks should I buy or sell?")
    ]
    
    for i, (label, question) in enumerate(quick_questions):
        with [qcol1, qcol2, qcol3][i]:
            if st.button(label, key=f"modal_q_{i}", use_container_width=True):
                st.session_state.ai_chat_history.append({"role": "user", "content": question})
                with st.spinner("Analyzing..."):
                    response = chat_with_assistant(
                        question,
                        st.session_state.analysis_results,
                        st.session_state.portfolio_data,
                        st.session_state.ai_chat_history
                    )
                    st.session_state.ai_chat_history.append({"role": "assistant", "content": response})
                st.rerun()
    
    # Input field
    col_input, col_btn = st.columns([5, 1])
    with col_input:
        user_input = st.text_input("Your question:", key="ai_modal_input", placeholder="Ask about your portfolio...", label_visibility="collapsed")
    with col_btn:
        send_clicked = st.button("Send", type="primary", use_container_width=True)
    
    if send_clicked and user_input:
        st.session_state.ai_chat_history.append({"role": "user", "content": user_input})
        with st.spinner("Thinking..."):
            response = chat_with_assistant(
                user_input,
                st.session_state.analysis_results,
                st.session_state.portfolio_data,
                st.session_state.ai_chat_history
            )
            st.session_state.ai_chat_history.append({"role": "assistant", "content": response})
        st.rerun()
    
    # Close and clear buttons
    bcol1, bcol2 = st.columns(2)
    with bcol1:
        if st.button("🗑️ Clear Chat", use_container_width=True):
            st.session_state.ai_chat_history = []
            st.rerun()
    with bcol2:
        if st.button("Close", use_container_width=True):
            st.session_state.show_ai_assistant = False
            st.rerun()

def render_ai_assistant():
    """Render the Portfolio Advisor chat interface (legacy tab version)"""
    from utils.ai_assistant import chat_with_assistant, get_quick_insights
    
    st.markdown("""
    <div style='background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 20px; border-radius: 12px; margin-bottom: 20px;'>
        <h2 style='color: white; margin: 0; font-size: 24px;'>✨ Alphalens Portfolio Advisor</h2>
        <p style='color: rgba(255,255,255,0.9); margin: 5px 0 0 0; font-size: 14px;'>Ask me anything about your portfolio analysis - metrics, recommendations, rebalancing strategies, and more!</p>
    </div>
    """, unsafe_allow_html=True)
    
    if 'ai_chat_history' not in st.session_state:
        st.session_state.ai_chat_history = []
    
    col1, col2 = st.columns([3, 1])
    
    with col2:
        st.markdown("**💡 Quick Questions**")
        quick_questions = [
            "Explain my portfolio performance",
            "Why are some stocks recommended as SELL?",
            "How is my sector diversification?",
            "How do I compare to NIFTY 50?",
            "What should I do to improve my portfolio?",
            "Explain the rebalancing suggestions"
        ]
        
        for q in quick_questions:
            if st.button(q, key=f"quick_{q[:20]}", use_container_width=True):
                st.session_state.pending_question = q
                st.rerun()
        
        st.markdown("---")
        if st.button("🗑️ Clear Chat", use_container_width=True):
            st.session_state.ai_chat_history = []
            st.rerun()
    
    with col1:
        chat_container = st.container()
        
        with chat_container:
            if not st.session_state.ai_chat_history:
                st.markdown("""
                <div style='background: #f8f9fa; padding: 20px; border-radius: 10px; text-align: center;'>
                    <p style='color: #666; margin: 0;'>👋 Hello! I'm your portfolio advisor. Ask me about:</p>
                    <ul style='text-align: left; color: #555; margin-top: 10px;'>
                        <li>Portfolio metrics and calculations</li>
                        <li>Sector allocation and diversification</li>
                        <li>Benchmark comparisons (NIFTY 50, Sensex)</li>
                        <li>Stock recommendations and rationale</li>
                        <li>Rebalancing strategies</li>
                        <li>Ways to improve your portfolio</li>
                    </ul>
                </div>
                """, unsafe_allow_html=True)
            else:
                for msg in st.session_state.ai_chat_history:
                    if msg["role"] == "user":
                        st.markdown(f"""
                        <div style='background: #e3f2fd; padding: 12px 15px; border-radius: 15px 15px 5px 15px; margin: 10px 0; margin-left: 20%;'>
                            <strong>You:</strong> {msg["content"]}
                        </div>
                        """, unsafe_allow_html=True)
                    else:
                        st.markdown(f"""
                        <div style='background: #f5f5f5; padding: 12px 15px; border-radius: 15px 15px 15px 5px; margin: 10px 0; margin-right: 10%;'>
                            <strong>✨ Alphalens:</strong><br>{msg["content"]}
                        </div>
                        """, unsafe_allow_html=True)
        
        if 'pending_question' in st.session_state:
            question = st.session_state.pending_question
            del st.session_state.pending_question
            
            st.session_state.ai_chat_history.append({"role": "user", "content": question})
            
            with st.spinner("Thinking..."):
                response = chat_with_assistant(
                    question,
                    st.session_state.analysis_results,
                    st.session_state.portfolio_data,
                    st.session_state.ai_chat_history
                )
                st.session_state.ai_chat_history.append({"role": "assistant", "content": response})
            st.rerun()
        
        user_input = st.chat_input("Ask about your portfolio analysis...")
        
        if user_input:
            st.session_state.ai_chat_history.append({"role": "user", "content": user_input})
            
            with st.spinner("Thinking..."):
                response = chat_with_assistant(
                    user_input,
                    st.session_state.analysis_results,
                    st.session_state.portfolio_data,
                    st.session_state.ai_chat_history
                )
                st.session_state.ai_chat_history.append({"role": "assistant", "content": response})
            st.rerun()

def render_partner_section():
    """Render Partner with Us section using Streamlit columns"""
    st.markdown("""
    <div style="text-align: center; margin-bottom: 40px; padding-top: 20px;">
        <h1 style="font-size: 42px; font-weight: 800; color: #1a1a2e; margin-bottom: 16px;">Partner with Us</h1>
        <p style="font-size: 18px; color: #666; line-height: 1.6;">
            Join hands with Alphalens to revolutionize portfolio analytics for Indian investors
        </p>
    </div>
    """, unsafe_allow_html=True)
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("""
        <div style="background: #fff; border: 1px solid #eef2f7; border-radius: 16px; padding: 32px; min-height: 200px;">
            <div style="font-size: 36px; margin-bottom: 16px;">🏦</div>
            <h3 style="font-size: 22px; font-weight: 700; color: #1a1a2e; margin-bottom: 12px;">Broking Partners</h3>
            <p style="color: #666; line-height: 1.7;">Integrate Alphalens into your platform to provide clients with advanced portfolio analytics and recommendations.</p>
        </div>
        """, unsafe_allow_html=True)
    
    with col2:
        st.markdown("""
        <div style="background: #fff; border: 1px solid #eef2f7; border-radius: 16px; padding: 32px; min-height: 200px;">
            <div style="font-size: 36px; margin-bottom: 16px;">💼</div>
            <h3 style="font-size: 22px; font-weight: 700; color: #1a1a2e; margin-bottom: 12px;">Wealth Advisors</h3>
            <p style="color: #666; line-height: 1.7;">Use our white-label solution to offer institutional-grade analysis to your high-net-worth clients.</p>
        </div>
        """, unsafe_allow_html=True)
    
    st.markdown("<br>", unsafe_allow_html=True)
    
    col3, col4 = st.columns(2)
    
    with col3:
        st.markdown("""
        <div style="background: #fff; border: 1px solid #eef2f7; border-radius: 16px; padding: 32px; min-height: 200px;">
            <div style="font-size: 36px; margin-bottom: 16px;">🎓</div>
            <h3 style="font-size: 22px; font-weight: 700; color: #1a1a2e; margin-bottom: 12px;">Educational Institutions</h3>
            <p style="color: #666; line-height: 1.7;">Partner with us to teach investment analysis and portfolio management to finance students.</p>
        </div>
        """, unsafe_allow_html=True)
    
    with col4:
        st.markdown("""
        <div style="background: #fff; border: 1px solid #eef2f7; border-radius: 16px; padding: 32px; min-height: 200px;">
            <div style="font-size: 36px; margin-bottom: 16px;">🤝</div>
            <h3 style="font-size: 22px; font-weight: 700; color: #1a1a2e; margin-bottom: 12px;">API Integration</h3>
            <p style="color: #666; line-height: 1.7;">Access our analytics engine via API to build custom solutions for your specific requirements.</p>
        </div>
        """, unsafe_allow_html=True)
    
    st.markdown("<br>", unsafe_allow_html=True)
    
    st.markdown("""
    <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 20px; padding: 40px; text-align: center;">
        <h2 style="color: white; font-size: 28px; font-weight: 700; margin-bottom: 16px;">Ready to Partner?</h2>
        <p style="color: rgba(255,255,255,0.9); font-size: 16px; margin-bottom: 24px;">Contact us at <strong>partners@thealphamarket.com</strong></p>
        <p style="color: rgba(255,255,255,0.8); font-size: 14px;">We'll get back to you within 24 hours</p>
    </div>
    """, unsafe_allow_html=True)


def render_features_page():
    """Render dedicated Features page with detailed feature descriptions"""
    st.markdown("""
    <div style="text-align: center; margin-bottom: 40px; padding-top: 20px;">
        <h1 style="font-size: 42px; font-weight: 800; color: #1a1a2e; margin-bottom: 16px;">Features</h1>
        <p style="font-size: 18px; color: #666; line-height: 1.6;">
            Comprehensive portfolio analysis tools designed for the Indian market
        </p>
    </div>
    """, unsafe_allow_html=True)
    
    # Feature 1: Performance Analytics
    col1, col2 = st.columns([1, 1])
    with col1:
        st.markdown("""
        <div style="padding: 30px;">
            <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); width: 60px; height: 60px; border-radius: 12px; display: flex; align-items: center; justify-content: center; margin-bottom: 20px;">
                <span style="font-size: 28px;">📊</span>
            </div>
            <h2 style="font-size: 28px; font-weight: 700; color: #1a1a2e; margin-bottom: 16px;">Performance Analytics</h2>
            <p style="color: #666; font-size: 16px; line-height: 1.8; margin-bottom: 20px;">
                Track your portfolio's complete performance history with detailed metrics including total returns, 
                absolute gains, win rate percentage, and identification of best and worst performers.
            </p>
            <ul style="color: #555; font-size: 15px; line-height: 2;">
                <li>Real-time portfolio valuation</li>
                <li>Historical performance tracking</li>
                <li>All-time high analysis for each stock</li>
                <li>Weighted average cost calculation</li>
            </ul>
        </div>
        """, unsafe_allow_html=True)
    with col2:
        st.markdown("""
        <div style="background: linear-gradient(135deg, #f8faff 0%, #eef2f7 100%); border-radius: 20px; padding: 40px; height: 100%; display: flex; align-items: center; justify-content: center;">
            <div style="text-align: center;">
                <div style="font-size: 80px; margin-bottom: 16px;">📈</div>
                <p style="color: #667eea; font-weight: 600;">Track Every Rupee</p>
            </div>
        </div>
        """, unsafe_allow_html=True)
    
    st.markdown("<hr style='margin: 40px 0; border: none; border-top: 1px solid #eef2f7;'>", unsafe_allow_html=True)
    
    # Feature 2: Risk Assessment
    col3, col4 = st.columns([1, 1])
    with col3:
        st.markdown("""
        <div style="background: linear-gradient(135deg, #fff5f5 0%, #fee2e2 100%); border-radius: 20px; padding: 40px; height: 100%; display: flex; align-items: center; justify-content: center;">
            <div style="text-align: center;">
                <div style="font-size: 80px; margin-bottom: 16px;">🎯</div>
                <p style="color: #dc2626; font-weight: 600;">Manage Risk Wisely</p>
            </div>
        </div>
        """, unsafe_allow_html=True)
    with col4:
        st.markdown("""
        <div style="padding: 30px;">
            <div style="background: linear-gradient(135deg, #dc2626 0%, #b91c1c 100%); width: 60px; height: 60px; border-radius: 12px; display: flex; align-items: center; justify-content: center; margin-bottom: 20px;">
                <span style="font-size: 28px;">⚠️</span>
            </div>
            <h2 style="font-size: 28px; font-weight: 700; color: #1a1a2e; margin-bottom: 16px;">Risk Assessment</h2>
            <p style="color: #666; font-size: 16px; line-height: 1.8; margin-bottom: 20px;">
                Understand your portfolio's risk profile with institutional-grade metrics including Beta, Sharpe Ratio, 
                Sortino Ratio, Maximum Drawdown, and volatility analysis.
            </p>
            <ul style="color: #555; font-size: 15px; line-height: 2;">
                <li>Risk Radar with 7-factor analysis</li>
                <li>Concentration risk alerts</li>
                <li>Sector exposure monitoring</li>
                <li>Tail risk assessment</li>
            </ul>
        </div>
        """, unsafe_allow_html=True)
    
    st.markdown("<hr style='margin: 40px 0; border: none; border-top: 1px solid #eef2f7;'>", unsafe_allow_html=True)
    
    # Feature 3: Expert Recommendations
    col5, col6 = st.columns([1, 1])
    with col5:
        st.markdown("""
        <div style="padding: 30px;">
            <div style="background: linear-gradient(135deg, #10b981 0%, #059669 100%); width: 60px; height: 60px; border-radius: 12px; display: flex; align-items: center; justify-content: center; margin-bottom: 20px;">
                <span style="font-size: 28px;">💡</span>
            </div>
            <h2 style="font-size: 28px; font-weight: 700; color: #1a1a2e; margin-bottom: 16px;">Expert Recommendations</h2>
            <p style="color: #666; font-size: 16px; line-height: 1.8; margin-bottom: 20px;">
                Receive data-driven BUY, HOLD, or SELL recommendations based on dual Value and Growth investing 
                frameworks with clear rationale for each suggestion.
            </p>
            <ul style="color: #555; font-size: 15px; line-height: 2;">
                <li>Value investing metrics analysis</li>
                <li>Growth momentum indicators</li>
                <li>Alternative stock suggestions</li>
                <li>Sector-relative comparisons</li>
            </ul>
        </div>
        """, unsafe_allow_html=True)
    with col6:
        st.markdown("""
        <div style="background: linear-gradient(135deg, #ecfdf5 0%, #d1fae5 100%); border-radius: 20px; padding: 40px; height: 100%; display: flex; align-items: center; justify-content: center;">
            <div style="text-align: center;">
                <div style="font-size: 80px; margin-bottom: 16px;">💡</div>
                <p style="color: #10b981; font-weight: 600;">Actionable Insights</p>
            </div>
        </div>
        """, unsafe_allow_html=True)
    
    st.markdown("<hr style='margin: 40px 0; border: none; border-top: 1px solid #eef2f7;'>", unsafe_allow_html=True)
    
    # Feature 4: Tax Impact
    col7, col8 = st.columns([1, 1])
    with col7:
        st.markdown("""
        <div style="background: linear-gradient(135deg, #fef3c7 0%, #fde68a 100%); border-radius: 20px; padding: 40px; height: 100%; display: flex; align-items: center; justify-content: center;">
            <div style="text-align: center;">
                <div style="font-size: 80px; margin-bottom: 16px;">💰</div>
                <p style="color: #d97706; font-weight: 600;">Optimize Your Taxes</p>
            </div>
        </div>
        """, unsafe_allow_html=True)
    with col8:
        st.markdown("""
        <div style="padding: 30px;">
            <div style="background: linear-gradient(135deg, #f59e0b 0%, #d97706 100%); width: 60px; height: 60px; border-radius: 12px; display: flex; align-items: center; justify-content: center; margin-bottom: 20px;">
                <span style="font-size: 28px;">💰</span>
            </div>
            <h2 style="font-size: 28px; font-weight: 700; color: #1a1a2e; margin-bottom: 16px;">Tax Impact Analysis</h2>
            <p style="color: #666; font-size: 16px; line-height: 1.8; margin-bottom: 20px;">
                Understand your tax liability with STCG/LTCG classification based on Indian tax laws, 
                including ₹1 lakh LTCG exemption tracking and tax harvesting opportunities.
            </p>
            <ul style="color: #555; font-size: 15px; line-height: 2;">
                <li>Short-term vs Long-term classification</li>
                <li>Estimated tax liability calculation</li>
                <li>Tax-loss harvesting suggestions</li>
                <li>Holding period optimization</li>
            </ul>
        </div>
        """, unsafe_allow_html=True)


def render_about_section():
    """Render About section using Streamlit columns"""
    st.markdown("""
    <div style="text-align: center; margin-bottom: 40px; padding-top: 20px;">
        <h1 style="font-size: 42px; font-weight: 800; color: #1a1a2e; margin-bottom: 16px;">About Alphalens</h1>
        <p style="font-size: 18px; color: #666; line-height: 1.6;">
            By Edhaz Financial Services - Empowering Indian Investors with Data-Driven Insights
        </p>
    </div>
    """, unsafe_allow_html=True)
    
    st.markdown("""
    <div style="background: #fff; border: 1px solid #eef2f7; border-radius: 16px; padding: 40px; margin-bottom: 32px;">
        <h2 style="font-size: 24px; font-weight: 700; color: #1a1a2e; margin-bottom: 20px;">Our Mission</h2>
        <p style="color: #555; font-size: 16px; line-height: 1.8; margin-bottom: 20px;">
            At Alphalens, we believe every investor deserves access to institutional-grade portfolio analytics. 
            Our mission is to democratize sophisticated investment analysis tools that were previously available 
            only to large financial institutions and wealthy individuals.
        </p>
        <p style="color: #555; font-size: 16px; line-height: 1.8;">
            We combine decades of investment research with cutting-edge technology to provide 
            actionable insights that help you make informed decisions about your portfolio.
        </p>
    </div>
    """, unsafe_allow_html=True)
    
    col1, col2, col3 = st.columns(3)
    
    with col1:
        st.markdown("""
        <div style="background: #f8faff; border-radius: 12px; padding: 24px; text-align: center;">
            <div style="font-size: 36px; color: #667eea; font-weight: 800; margin-bottom: 8px;">50+</div>
            <div style="color: #666; font-size: 14px;">Metrics Analyzed</div>
        </div>
        """, unsafe_allow_html=True)
    
    with col2:
        st.markdown("""
        <div style="background: #f8faff; border-radius: 12px; padding: 24px; text-align: center;">
            <div style="font-size: 36px; color: #667eea; font-weight: 800; margin-bottom: 8px;">10</div>
            <div style="color: #666; font-size: 14px;">Analysis Layers</div>
        </div>
        """, unsafe_allow_html=True)
    
    with col3:
        st.markdown("""
        <div style="background: #f8faff; border-radius: 12px; padding: 24px; text-align: center;">
            <div style="font-size: 36px; color: #667eea; font-weight: 800; margin-bottom: 8px;">2</div>
            <div style="color: #666; font-size: 14px;">Investment Frameworks</div>
        </div>
        """, unsafe_allow_html=True)
    
    st.markdown("<br>", unsafe_allow_html=True)
    
    col4, col5 = st.columns(2)
    
    with col4:
        st.markdown("""
        <div style="background: #fff; border: 1px solid #eef2f7; border-radius: 16px; padding: 32px;">
            <p style="color: #888; font-size: 13px; margin-bottom: 4px;">Email</p>
            <p style="color: #333; font-size: 16px; font-weight: 600;">hello@thealphamarket.com</p>
        </div>
        """, unsafe_allow_html=True)
    
    with col5:
        st.markdown("""
        <div style="background: #fff; border: 1px solid #eef2f7; border-radius: 16px; padding: 32px;">
            <p style="color: #888; font-size: 13px; margin-bottom: 4px;">Location</p>
            <p style="color: #333; font-size: 16px; font-weight: 600;">Mumbai, India</p>
        </div>
        """, unsafe_allow_html=True)


def display_upload_page():
    """Display dedicated upload page for authenticated users"""
    render_top_header()
    
    st.markdown("<br>", unsafe_allow_html=True)
    
    col1, col2, col3 = st.columns([0.2, 2.6, 0.2])
    with col2:
        st.markdown("""
        <div style='text-align: center; padding: 40px 0 20px 0;'>
            <h1 style='font-size: 36px; font-weight: 700; color: #111827; margin-bottom: 12px;'>Analyze Your Portfolio</h1>
            <p style='font-size: 18px; color: #6b7280;'>Upload your portfolio CSV file to get comprehensive analysis and insights.</p>
        </div>
        """, unsafe_allow_html=True)
        
        st.markdown("""
        <div style='background: linear-gradient(135deg, #e8f5e9 0%, #f1f8e9 100%); 
                    padding: 24px; border-radius: 16px; border: 1px solid #c8e6c9; 
                    margin-bottom: 24px; text-align: center;'>
            <p style='color: #2e7d32; margin: 0; font-size: 18px; font-weight: 600;'>
                ✅ You're logged in! Upload your portfolio to begin analysis.
            </p>
        </div>
        """, unsafe_allow_html=True)
        
        uploaded_file = st.file_uploader(
            "Upload your portfolio CSV",
            type=['csv'],
            help="Upload a CSV file with columns: Stock Name, Buy Price, Buy Date, Quantity"
        )
        
        if uploaded_file is not None:
            try:
                portfolio_df = pd.read_csv(uploaded_file)
                required_columns = ['Stock Name', 'Buy Price', 'Buy Date', 'Quantity']
                missing_columns = [col for col in required_columns if col not in portfolio_df.columns]
                
                if missing_columns:
                    st.error(f"Missing required columns: {', '.join(missing_columns)}")
                else:
                    portfolio_df['Buy Date'] = pd.to_datetime(portfolio_df['Buy Date'])
                    portfolio_df['Buy Price'] = pd.to_numeric(portfolio_df['Buy Price'], errors='coerce')
                    portfolio_df['Quantity'] = pd.to_numeric(portfolio_df['Quantity'], errors='coerce')
                    portfolio_df = portfolio_df.dropna()
                    
                    if len(portfolio_df) == 0:
                        st.error("No valid data found in the uploaded file. Please check the format.")
                    else:
                        st.session_state.portfolio_data = portfolio_df
                        st.session_state.uploaded_file_name = uploaded_file.name
                        st.success(f"Successfully loaded {len(portfolio_df)} stocks from your portfolio!")
                        st.rerun()
            except Exception as e:
                st.error(f"Error reading file: {str(e)}")
        
        st.markdown("<br>", unsafe_allow_html=True)
        
        st.markdown("""
        <div style='background: #f9fafb; padding: 24px; border-radius: 12px; border: 1px solid #e5e7eb;'>
            <h3 style='font-size: 18px; font-weight: 700; color: #111827; margin-bottom: 14px;'>CSV Format Requirements</h3>
            <p style='font-size: 14px; color: #6b7280; line-height: 1.5; margin-bottom: 14px;'>
                Your CSV file should contain the following columns:
            </p>
            <ul style='font-size: 14px; color: #4b5563; line-height: 1.8; padding-left: 18px; margin: 0;'>
                <li><strong>Stock Name</strong> - Name or symbol of the stock</li>
                <li><strong>Buy Date</strong> - Purchase date (DD-MM-YYYY)</li>
                <li><strong>Buy Price</strong> - Price per share at purchase</li>
                <li><strong>Quantity</strong> - Number of shares</li>
            </ul>
        </div>
        """, unsafe_allow_html=True)
        
        st.markdown("<br>", unsafe_allow_html=True)
        
        if st.button("← Back to Home", use_container_width=True):
            st.session_state.show_upload_page = False
            st.rerun()


def display_welcome_screen():
    """Display modern, portfoliosmith-style welcome screen"""
    
    if st.session_state.show_login:
        render_top_header()
        display_login_modal()
        return
    
    if st.session_state.show_signup:
        render_top_header()
        display_signup_modal()
        return
    
    render_top_header()
    
    # Handle navigation sections
    if st.session_state.nav_section == "partner":
        render_partner_section()
        if st.button("← Back to Home", key="back_from_partner"):
            st.session_state.nav_section = None
            st.rerun()
        return
    
    if st.session_state.nav_section == "about":
        render_about_section()
        if st.button("← Back to Home", key="back_from_about"):
            st.session_state.nav_section = None
            st.rerun()
        return
    
    if st.session_state.nav_section == "methodology":
        from components.methodology import Methodology
        methodology = Methodology()
        methodology.render()
        if st.button("← Back to Home", key="back_from_methodology"):
            st.session_state.nav_section = None
            st.rerun()
        return
    
    if st.session_state.nav_section == "features":
        render_features_page()
        if st.button("← Back to Home", key="back_from_features"):
            st.session_state.nav_section = None
            st.rerun()
        return
    
    def show_signup():
        st.session_state.show_signup = True
        st.rerun()
    
    def show_login():
        st.session_state.show_login = True
        st.rerun()
    
    render_modern_homepage(
        authenticated=st.session_state.authenticated,
        show_login_callback=show_login,
        show_signup_callback=show_signup,
        analyze_callback=None
    )
    
    
    render_methodology_section()
    render_metrics_section()
    
    if st.session_state.authenticated:
        st.markdown("<br>", unsafe_allow_html=True)
        col1, col2, col3 = st.columns([0.3, 2, 0.3])
        with col2:
            st.markdown("""
            <div style='background: linear-gradient(135deg, #e8f5e9 0%, #f1f8e9 100%); 
                        padding: 24px; border-radius: 16px; border: 1px solid #c8e6c9; 
                        margin-bottom: 24px; text-align: center;'>
                <p style='color: #2e7d32; margin: 0; font-size: 18px; font-weight: 600;'>
                    ✅ You're logged in! Upload your portfolio to begin analysis.
                </p>
            </div>
            """, unsafe_allow_html=True)
            
            uploaded_file = st.file_uploader(
                "Upload your portfolio CSV",
                type=['csv'],
                help="Upload a CSV file with columns: Stock Name, Buy Price, Buy Date, Quantity"
            )
            
            if uploaded_file is not None:
                try:
                    portfolio_df = pd.read_csv(uploaded_file)
                    required_columns = ['Stock Name', 'Buy Price', 'Buy Date', 'Quantity']
                    missing_columns = [col for col in required_columns if col not in portfolio_df.columns]
                    
                    if missing_columns:
                        st.error(f"Missing required columns: {', '.join(missing_columns)}")
                    else:
                        portfolio_df['Buy Date'] = pd.to_datetime(portfolio_df['Buy Date'])
                        portfolio_df['Buy Price'] = pd.to_numeric(portfolio_df['Buy Price'], errors='coerce')
                        portfolio_df['Quantity'] = pd.to_numeric(portfolio_df['Quantity'], errors='coerce')
                        portfolio_df = portfolio_df.dropna()
                        
                        if len(portfolio_df) == 0:
                            st.error("No valid data found in the uploaded file.")
                        else:
                            st.success(f"✅ Successfully loaded {len(portfolio_df)} stocks")
                            st.session_state.portfolio_data = portfolio_df
                            st.session_state.uploaded_file_name = uploaded_file.name
                            
                            if st.button("🚀 Analyze My Portfolio", type="primary", use_container_width=True):
                                st.session_state.analysis_complete = False
                                with st.spinner("🔄 Fetching market data and analyzing portfolio..."):
                                    analyze_portfolio()
                                
                except Exception as e:
                    st.error(f"Error reading file: {str(e)}")
        
            st.markdown("<br>", unsafe_allow_html=True)
            col_a, col_b, col_c = st.columns([1, 1, 1])
            with col_b:
                sample_data = {
                    'Stock Name': ['RELIANCE', 'TCS', 'INFY', 'HDFCBANK'],
                    'Buy Price': [2500, 3200, 1800, 1600],
                    'Buy Date': ['2023-01-15', '2023-02-20', '2023-03-10', '2023-04-05'],
                    'Quantity': [10, 15, 20, 25]
                }
                sample_df = pd.DataFrame(sample_data)
                csv = sample_df.to_csv(index=False)
                st.download_button(
                    label="📥 Download Sample CSV",
                    data=csv,
                    file_name="portfolio_sample.csv",
                    mime="text/csv",
                    use_container_width=True
                )
    
    render_features_section()
    
    render_insights_section()
    
    render_how_it_works_section()
    
    render_cta_section(st.session_state.authenticated, show_signup)
    
    render_footer()

def display_portfolio_preview():
    """Display portfolio preview after upload"""
    
    render_auth_header()
    
    if st.session_state.show_login:
        display_login_modal()
        return
    
    if st.session_state.show_signup:
        display_signup_modal()
        return
    
    st.markdown('<div class="content-section">', unsafe_allow_html=True)
    col1, col2, col3 = st.columns([0.5, 2, 0.5])
    with col2:
        st.markdown("""
        <div style='
            background-color: #e8f4f8;
            border-left: 5px solid #FF6B35;
            border-radius: 8px;
            padding: 15px;
            text-align: center;
            margin-bottom: 15px;
            margin-top: 10px;
        '>
            <p style='color: #333; font-size: 18px; margin: 0;'>
                ✅ Portfolio uploaded successfully! Click <strong>'Analyze Portfolio'</strong> to continue
            </p>
        </div>
        """, unsafe_allow_html=True)
        
        st.subheader("📋 Portfolio Preview")
        st.dataframe(st.session_state.portfolio_data, use_container_width=True)
        
        with st.expander("📜 Terms & Disclaimer - Please Read Before Analyzing", expanded=not st.session_state.get('analysis_disclaimer_accepted', False)):
            st.markdown("""
**Disclaimer – Portfolio Analysis, Investment Advice & Rebalancing**

The portfolio analysis, investment advice, recommendations, and rebalancing suggestions displayed on thealphalens.com are algorithmic outputs generated by proprietary Growth and Value investing models. These models are based on widely accepted investment frameworks using quantitative financial, price, and momentum data.

**Important:**
- This tool **does not provide personalised investment advice** and does not consider your individual financial situation, investment objectives, risk appetite, tax status, or liquidity needs.
- The analysis and suggestions are purely **model-driven, informational, and educational** in nature.
- **Past performance does not guarantee future results.** Financial markets are inherently volatile.

**By proceeding, you acknowledge that:**
1. All recommendations are **indicative and based on historical data assumptions.**
2. You **assume full responsibility** for any investment decisions taken based on this analysis.
3. thealphalens.com and its affiliates **shall not be held liable** for any losses arising from actions taken based on these recommendations.

You are advised to **consult a SEBI-registered investment advisor** before making investment decisions.
            """)
            
            analysis_consent = st.checkbox(
                "I have read and understood the disclaimer. I accept full responsibility for my investment decisions.",
                key="analysis_disclaimer_checkbox"
            )
            
            if analysis_consent:
                st.session_state.analysis_disclaimer_accepted = True
                st.success("Thank you! You can now analyze your portfolio.")
        
        can_analyze = st.session_state.get('analysis_disclaimer_accepted', False)
        
        if can_analyze:
            if st.button("🔍 Analyze Portfolio", type="primary", use_container_width=True):
                if not st.session_state.authenticated:
                    st.warning("Please login or register to analyze your portfolio")
                    st.session_state.show_login = True
                    st.rerun()
                else:
                    st.session_state.analysis_complete = False
                    with st.spinner("🔄 Fetching market data and analyzing portfolio..."):
                        analyze_portfolio()
        else:
            st.button("🔍 Analyze Portfolio", type="secondary", use_container_width=True, disabled=True)
            st.caption("Please read and accept the disclaimer above to enable portfolio analysis.")
    st.markdown('</div>', unsafe_allow_html=True)

def add_footer():
    """Add footer with disclaimer and company details"""
    st.markdown("""
    <div style='background: linear-gradient(180deg, #f8faff 0%, #eef2f7 100%); padding: 50px 40px; margin-top: 60px; border-top: 1px solid #e5e7eb;'>
        <div style='max-width: 900px; margin: 0 auto; text-align: center;'>
            <p style='font-size: 15px; color: #555; line-height: 1.8; margin-bottom: 24px;'>
                <strong>Disclaimer:</strong> The information provided is for informational purposes only 
                and should not be considered financial advice. Please consult a qualified financial advisor 
                before making investment decisions. Past performance does not guarantee future results.
            </p>
            <div style='border-top: 1px solid #ddd; padding-top: 24px; margin-top: 24px;'>
                <p style='font-size: 16px; color: #1a1a2e; font-weight: 600; margin-bottom: 8px;'>
                    Alphalens by Edhaz Financial Services Private Limited
                </p>
                <p style='font-size: 14px; color: #666; margin-bottom: 12px;'>
                    Alpine Eco, Doddenekkundi, K R Puram Hobli, Bangalore 560037
                </p>
                <p style='font-size: 14px; color: #666;'>
                    <a href='mailto:hello@thealphamarket.com' style='color: #667eea; text-decoration: none;'>hello@thealphamarket.com</a>
                    <span style='margin: 0 12px; color: #ccc;'>|</span>
                    <a href='tel:+919108967788' style='color: #667eea; text-decoration: none;'>+91-91089 67788</a>
                </p>
            </div>
        </div>
    </div>
    """, unsafe_allow_html=True)

if __name__ == "__main__":
    main()
